name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - feature/13-configuracao-firebase

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Variáveis de ambiente ---
      - name: Create .env.production
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL_HML }}" > .env.production

      # --- Instalar dependências e build ---
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # --- Iniciar o front para o Cypress ---
      - name: Start Frontend
        run: |
          npm run preview -- --port 5550 &
          sleep 5

      # --- Instalar Cypress ---
      - name: Install Cypress
        run: npm install cypress start-server-and-test --save-dev

      # --- Rodar testes Cypress ---
      - name: Run Cypress Tests
        env:
          CYPRESS_baseUrl: "http://localhost:5550"
        run: npm run test:e2e

      # --- Deploy Firebase Hosting ---
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STOCKFLOW_SHOPP }}
          channelId: live
          projectId: stockflow-shopp
